services:
  cleanup:
    entrypoint:
      - /bin/rm
      - -fr
      - dist
      - src/notch.egg-info
    image: ghcr.io/williamjacksn/notch-dev
    init: true
    volumes:
      - ./:/home/python/notch
    working_dir: /home/python/notch

  py-build:
    entrypoint:
      - /home/python/venv/bin/python
      - -m
      - build
    image: ghcr.io/williamjacksn/notch-dev
    init: true
    volumes:
      - ./:/home/python/notch
    working_dir: /home/python/notch

  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/williamjacksn/notch-dev
    init: true
    volumes:
      - ./:/home/python/notch
    working_dir: /home/python/notch
