services:
  cleanup:
    entrypoint:
      - /bin/rm
      - -fr
      - dist
      - src/logs.egg-info
    image: ghcr.io/williamjacksn/logs-dev
    init: true
    volumes:
      - ./:/home/python/logs
    working_dir: /home/python/logs

  py-build:
    entrypoint:
      - /home/python/venv/bin/python
      - -m
      - build
    image: ghcr.io/williamjacksn/logs-dev
    init: true
    volumes:
      - ./:/home/python/logs
    working_dir: /home/python/logs

  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/williamjacksn/logs-dev
    init: true
    volumes:
      - ./:/home/python/logs
    working_dir: /home/python/logs

  twine-upload:
    entrypoint:
      - /home/python/venv/bin/twine
      - upload
      - --skip-existing
      - --verbose
      - dist/*
    environment:
      TWINE_PASSWORD:
      TWINE_USERNAME:
    image: ghcr.io/williamjacksn/logs-dev
    init: true
    volumes:
      - ./:/home/python/logs
    working_dir: /home/python/logs
